[package]
name = "procc-ll"
version = "0.1.0"
edition = "2021"
description = "processor of tokens for rust"
license = "Apache-2.0"
authors = ["k3nder"]
repository = "https://github.com/k3nder/processor"

[dependencies]
regex = "1.11.0"
log = "0.4.22"
env_logger = "0.11.5"
lazy_static = "1.5.0"